# Generated by Django 5.2.5 on 2025-09-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='plate_no',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
