# Generated by Django 5.2.5 on 2025-09-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_cart_plate_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='delivery_fee',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='vendors',
            name='plate_price',
            field=models.IntegerField(default=50),
        ),
    ]
