# Generated by Django 5.2.5 on 2025-09-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0003_vendors_delivery_fee_vendors_plate_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='plate_price',
            field=models.IntegerField(default=200),
        ),
    ]
