# Generated by Django 5.2.5 on 2025-10-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0005_location_alter_order_delivery_no_order_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
    ]
