# Generated by Django 5.2.5 on 2025-10-24 22:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0006_remove_order_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiter',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodie.location'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='phone_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 11 digits.', regex='^\\d{11}$')]),
        ),
    ]
